{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "b60415a2-6fe6-44c9-b829-ce971deca4ff",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: requests in c:\\users\\shiim\\anaconda3\\lib\\site-packages (2.32.3)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from requests) (3.3.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from requests) (3.7)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from requests) (2.2.3)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from requests) (2026.1.4)\n",
      "Requirement already satisfied: apache-airflow in c:\\users\\shiim\\anaconda3\\lib\\site-packages (2.11.0)\n",
      "Requirement already satisfied: alembic<2.0,>=1.13.1 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (1.13.3)\n",
      "Requirement already satisfied: argcomplete>=1.10 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (3.6.3)\n",
      "Requirement already satisfied: asgiref>=2.3.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (3.11.0)\n",
      "Requirement already satisfied: attrs>=22.1.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (25.4.0)\n",
      "Requirement already satisfied: blinker>=1.6.2 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (1.6.2)\n",
      "Requirement already satisfied: colorlog>=6.8.2 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (6.10.1)\n",
      "Requirement already satisfied: configupdater>=3.1.1 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (3.2)\n",
      "Requirement already satisfied: connexion<3.0,>=2.14.2 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from connexion[flask]<3.0,>=2.14.2->apache-airflow) (2.14.2)\n",
      "Requirement already satisfied: cron-descriptor>=1.2.24 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (2.0.6)\n",
      "Requirement already satisfied: croniter>=2.0.2 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (6.0.0)\n",
      "Requirement already satisfied: cryptography>=41.0.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (43.0.0)\n",
      "Requirement already satisfied: deprecated>=1.2.13 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (1.3.1)\n",
      "Requirement already satisfied: dill>=0.2.2 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (0.3.8)\n",
      "Requirement already satisfied: flask-caching>=2.0.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (2.3.1)\n",
      "Requirement already satisfied: flask-session<0.6,>=0.4.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (0.5.0)\n",
      "Requirement already satisfied: flask-wtf>=1.1.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (1.2.2)\n",
      "Requirement already satisfied: flask<2.3,>=2.2.1 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (2.2.5)\n",
      "Requirement already satisfied: fsspec>=2023.10.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (2026.3.0)\n",
      "Requirement already satisfied: google-re2>=1.1 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (1.1.20251105)\n",
      "Requirement already satisfied: gunicorn>=20.1.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (23.0.0)\n",
      "Requirement already satisfied: httpx>=0.25.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (0.28.1)\n",
      "Requirement already satisfied: itsdangerous>=2.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (2.2.0)\n",
      "Requirement already satisfied: jinja2>=3.0.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (3.1.6)\n",
      "Requirement already satisfied: jsonschema>=4.18.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (4.23.0)\n",
      "Requirement already satisfied: lazy-object-proxy>=1.2.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (1.10.0)\n",
      "Requirement already satisfied: linkify-it-py>=2.0.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (2.0.0)\n",
      "Requirement already satisfied: lockfile>=0.12.2 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (0.12.2)\n",
      "Requirement already satisfied: markdown-it-py>=2.1.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (2.2.0)\n",
      "Requirement already satisfied: markupsafe>=1.1.1 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (2.1.3)\n",
      "Requirement already satisfied: marshmallow-oneofschema>=2.0.1 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (3.2.0)\n",
      "Requirement already satisfied: mdit-py-plugins>=0.3.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (0.3.0)\n",
      "Requirement already satisfied: methodtools>=0.4.7 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (0.4.7)\n",
      "Requirement already satisfied: opentelemetry-api>=1.24.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (1.39.1)\n",
      "Requirement already satisfied: opentelemetry-exporter-otlp>=1.24.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (1.39.1)\n",
      "Requirement already satisfied: packaging>=23.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (25.0)\n",
      "Requirement already satisfied: pathspec>=0.9.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (0.10.3)\n",
      "Requirement already satisfied: pendulum<4.0,>=3.0.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (3.1.0)\n",
      "Requirement already satisfied: pluggy>=1.5.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (1.6.0)\n",
      "Requirement already satisfied: psutil>=5.8.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (7.2.1)\n",
      "Requirement already satisfied: pygments>=2.0.1 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (2.15.1)\n",
      "Requirement already satisfied: pyjwt>=2.0.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (2.10.1)\n",
      "Requirement already satisfied: python-daemon>=3.0.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (3.1.2)\n",
      "Requirement already satisfied: python-dateutil>=2.7.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (2.9.0.post0)\n",
      "Requirement already satisfied: python-nvd3>=0.15.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (0.16.0)\n",
      "Requirement already satisfied: python-slugify>=5.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (8.0.4)\n",
      "Requirement already satisfied: requests<3,>=2.27.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (2.32.3)\n",
      "Requirement already satisfied: requests-toolbelt>=0.4.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (1.0.0)\n",
      "Requirement already satisfied: rfc3339-validator>=0.1.4 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (0.1.4)\n",
      "Requirement already satisfied: rich-argparse>=1.0.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (1.7.2)\n",
      "Requirement already satisfied: rich>=12.4.4 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (13.7.1)\n",
      "Requirement already satisfied: setproctitle>=1.3.3 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (1.3.7)\n",
      "Requirement already satisfied: sqlalchemy<2.0,>=1.4.36 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (1.4.54)\n",
      "Requirement already satisfied: sqlalchemy-jsonfield>=1.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (1.0.2)\n",
      "Requirement already satisfied: tabulate>=0.7.5 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (0.9.0)\n",
      "Requirement already satisfied: tenacity!=8.2.0,>=8.0.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (9.1.2)\n",
      "Requirement already satisfied: termcolor>=1.1.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (3.3.0)\n",
      "Requirement already satisfied: universal-pathlib!=0.2.4,>=0.2.2 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (0.2.6)\n",
      "Requirement already satisfied: werkzeug<3,>=2.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (2.2.3)\n",
      "Requirement already satisfied: apache-airflow-providers-common-compat in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (1.14.3)\n",
      "Requirement already satisfied: apache-airflow-providers-common-io in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (1.7.0)\n",
      "Requirement already satisfied: apache-airflow-providers-common-sql in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (1.34.0)\n",
      "Requirement already satisfied: apache-airflow-providers-fab>=1.0.2 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (1.5.3)\n",
      "Requirement already satisfied: apache-airflow-providers-ftp in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (3.14.0)\n",
      "Requirement already satisfied: apache-airflow-providers-http in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (5.6.2)\n",
      "Requirement already satisfied: apache-airflow-providers-imap in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (3.10.2)\n",
      "Requirement already satisfied: apache-airflow-providers-smtp in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (2.4.1)\n",
      "Requirement already satisfied: apache-airflow-providers-sqlite in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow) (4.2.0)\n",
      "Requirement already satisfied: Mako in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from alembic<2.0,>=1.13.1->apache-airflow) (1.2.3)\n",
      "Requirement already satisfied: typing-extensions>=4 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from alembic<2.0,>=1.13.1->apache-airflow) (4.15.0)\n",
      "Requirement already satisfied: clickclick<21,>=1.2 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from connexion<3.0,>=2.14.2->connexion[flask]<3.0,>=2.14.2->apache-airflow) (20.10.2)\n",
      "Requirement already satisfied: PyYAML<7,>=5.1 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from connexion<3.0,>=2.14.2->connexion[flask]<3.0,>=2.14.2->apache-airflow) (6.0.1)\n",
      "Requirement already satisfied: inflection<0.6,>=0.3.1 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from connexion<3.0,>=2.14.2->connexion[flask]<3.0,>=2.14.2->apache-airflow) (0.5.1)\n",
      "Requirement already satisfied: click>=4.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from clickclick<21,>=1.2->connexion<3.0,>=2.14.2->connexion[flask]<3.0,>=2.14.2->apache-airflow) (8.1.7)\n",
      "Requirement already satisfied: cachelib in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from flask-session<0.6,>=0.4.0->apache-airflow) (0.13.0)\n",
      "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from jsonschema>=4.18.0->apache-airflow) (2023.7.1)\n",
      "Requirement already satisfied: referencing>=0.28.4 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from jsonschema>=4.18.0->apache-airflow) (0.30.2)\n",
      "Requirement already satisfied: rpds-py>=0.7.1 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from jsonschema>=4.18.0->apache-airflow) (0.10.6)\n",
      "Requirement already satisfied: tzdata>=2020.1 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from pendulum<4.0,>=3.0.0->apache-airflow) (2023.3)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from requests<3,>=2.27.0->apache-airflow) (3.3.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from requests<3,>=2.27.0->apache-airflow) (3.7)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from requests<3,>=2.27.0->apache-airflow) (2.2.3)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from requests<3,>=2.27.0->apache-airflow) (2026.1.4)\n",
      "Requirement already satisfied: greenlet!=0.4.17 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from sqlalchemy<2.0,>=1.4.36->apache-airflow) (3.0.1)\n",
      "Requirement already satisfied: flask-appbuilder==4.5.3 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow-providers-fab>=1.0.2->apache-airflow) (4.5.3)\n",
      "Requirement already satisfied: flask-login>=0.6.2 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow-providers-fab>=1.0.2->apache-airflow) (0.6.3)\n",
      "Requirement already satisfied: jmespath>=0.7.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow-providers-fab>=1.0.2->apache-airflow) (1.0.1)\n",
      "Requirement already satisfied: apispec<7,>=6.0.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apispec[yaml]<7,>=6.0.0->flask-appbuilder==4.5.3->apache-airflow-providers-fab>=1.0.2->apache-airflow) (6.9.0)\n",
      "Requirement already satisfied: colorama<1,>=0.3.9 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from flask-appbuilder==4.5.3->apache-airflow-providers-fab>=1.0.2->apache-airflow) (0.4.6)\n",
      "Requirement already satisfied: email-validator>=1.0.5 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from flask-appbuilder==4.5.3->apache-airflow-providers-fab>=1.0.2->apache-airflow) (2.3.0)\n",
      "Requirement already satisfied: Flask-Babel<3,>=1 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from flask-appbuilder==4.5.3->apache-airflow-providers-fab>=1.0.2->apache-airflow) (2.0.0)\n",
      "Requirement already satisfied: Flask-Limiter<4,>3 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from flask-appbuilder==4.5.3->apache-airflow-providers-fab>=1.0.2->apache-airflow) (3.12)\n",
      "Requirement already satisfied: Flask-SQLAlchemy<3,>=2.4 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from flask-appbuilder==4.5.3->apache-airflow-providers-fab>=1.0.2->apache-airflow) (2.5.1)\n",
      "Requirement already satisfied: Flask-JWT-Extended<5.0.0,>=4.0.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from flask-appbuilder==4.5.3->apache-airflow-providers-fab>=1.0.2->apache-airflow) (4.7.1)\n",
      "Requirement already satisfied: marshmallow<4,>=3.18.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from flask-appbuilder==4.5.3->apache-airflow-providers-fab>=1.0.2->apache-airflow) (3.26.2)\n",
      "Requirement already satisfied: marshmallow-sqlalchemy<0.29.0,>=0.22.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from flask-appbuilder==4.5.3->apache-airflow-providers-fab>=1.0.2->apache-airflow) (0.28.2)\n",
      "Requirement already satisfied: prison<1.0.0,>=0.2.1 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from flask-appbuilder==4.5.3->apache-airflow-providers-fab>=1.0.2->apache-airflow) (0.2.1)\n",
      "Requirement already satisfied: sqlalchemy-utils<1,>=0.32.21 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from flask-appbuilder==4.5.3->apache-airflow-providers-fab>=1.0.2->apache-airflow) (0.42.1)\n",
      "Requirement already satisfied: WTForms<4 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from flask-appbuilder==4.5.3->apache-airflow-providers-fab>=1.0.2->apache-airflow) (3.2.1)\n",
      "Requirement already satisfied: pytz in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from Flask-Babel<3,>=1->flask-appbuilder==4.5.3->apache-airflow-providers-fab>=1.0.2->apache-airflow) (2024.1)\n",
      "Requirement already satisfied: Babel>=2.3 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from Flask-Babel<3,>=1->flask-appbuilder==4.5.3->apache-airflow-providers-fab>=1.0.2->apache-airflow) (2.17.0)\n",
      "Requirement already satisfied: limits>=3.13 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from Flask-Limiter<4,>3->flask-appbuilder==4.5.3->apache-airflow-providers-fab>=1.0.2->apache-airflow) (5.6.0)\n",
      "Requirement already satisfied: ordered-set<5,>4 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from Flask-Limiter<4,>3->flask-appbuilder==4.5.3->apache-airflow-providers-fab>=1.0.2->apache-airflow) (4.1.0)\n",
      "Requirement already satisfied: six in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from prison<1.0.0,>=0.2.1->flask-appbuilder==4.5.3->apache-airflow-providers-fab>=1.0.2->apache-airflow) (1.16.0)\n",
      "Requirement already satisfied: cffi>=1.12 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from cryptography>=41.0.0->apache-airflow) (1.17.1)\n",
      "Requirement already satisfied: pycparser in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from cffi>=1.12->cryptography>=41.0.0->apache-airflow) (2.21)\n",
      "Requirement already satisfied: wrapt<3,>=1.10 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from deprecated>=1.2.13->apache-airflow) (1.14.1)\n",
      "Requirement already satisfied: dnspython>=2.0.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from email-validator>=1.0.5->flask-appbuilder==4.5.3->apache-airflow-providers-fab>=1.0.2->apache-airflow) (2.8.0)\n",
      "Requirement already satisfied: anyio in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from httpx>=0.25.0->apache-airflow) (4.13.0)\n",
      "Requirement already satisfied: httpcore==1.* in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from httpx>=0.25.0->apache-airflow) (1.0.2)\n",
      "Requirement already satisfied: h11<0.15,>=0.13 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from httpcore==1.*->httpx>=0.25.0->apache-airflow) (0.14.0)\n",
      "Requirement already satisfied: uc-micro-py in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from linkify-it-py>=2.0.0->apache-airflow) (1.0.1)\n",
      "Requirement already satisfied: mdurl~=0.1 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from markdown-it-py>=2.1.0->apache-airflow) (0.1.0)\n",
      "Requirement already satisfied: wirerope>=0.4.7 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from methodtools>=0.4.7->apache-airflow) (1.0.0)\n",
      "Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from opentelemetry-api>=1.24.0->apache-airflow) (7.0.1)\n",
      "Requirement already satisfied: zipp>=0.5 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api>=1.24.0->apache-airflow) (3.17.0)\n",
      "Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc==1.39.1 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from opentelemetry-exporter-otlp>=1.24.0->apache-airflow) (1.39.1)\n",
      "Requirement already satisfied: opentelemetry-exporter-otlp-proto-http==1.39.1 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from opentelemetry-exporter-otlp>=1.24.0->apache-airflow) (1.39.1)\n",
      "Requirement already satisfied: googleapis-common-protos~=1.57 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from opentelemetry-exporter-otlp-proto-grpc==1.39.1->opentelemetry-exporter-otlp>=1.24.0->apache-airflow) (1.72.0)\n",
      "Requirement already satisfied: grpcio<2.0.0,>=1.63.2 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from opentelemetry-exporter-otlp-proto-grpc==1.39.1->opentelemetry-exporter-otlp>=1.24.0->apache-airflow) (1.80.0)\n",
      "Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.39.1 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from opentelemetry-exporter-otlp-proto-grpc==1.39.1->opentelemetry-exporter-otlp>=1.24.0->apache-airflow) (1.39.1)\n",
      "Requirement already satisfied: opentelemetry-proto==1.39.1 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from opentelemetry-exporter-otlp-proto-grpc==1.39.1->opentelemetry-exporter-otlp>=1.24.0->apache-airflow) (1.39.1)\n",
      "Requirement already satisfied: opentelemetry-sdk~=1.39.1 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from opentelemetry-exporter-otlp-proto-grpc==1.39.1->opentelemetry-exporter-otlp>=1.24.0->apache-airflow) (1.39.1)\n",
      "Requirement already satisfied: protobuf<7.0,>=5.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from opentelemetry-proto==1.39.1->opentelemetry-exporter-otlp-proto-grpc==1.39.1->opentelemetry-exporter-otlp>=1.24.0->apache-airflow) (6.33.6)\n",
      "Requirement already satisfied: opentelemetry-semantic-conventions==0.60b1 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from opentelemetry-sdk~=1.39.1->opentelemetry-exporter-otlp-proto-grpc==1.39.1->opentelemetry-exporter-otlp>=1.24.0->apache-airflow) (0.60b1)\n",
      "Requirement already satisfied: text-unidecode>=1.3 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from python-slugify>=5.0->apache-airflow) (1.3)\n",
      "Requirement already satisfied: sqlparse>=0.5.1 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow-providers-common-sql->apache-airflow) (0.5.5)\n",
      "Requirement already satisfied: more-itertools>=9.0.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow-providers-common-sql->apache-airflow) (10.3.0)\n",
      "Requirement already satisfied: aiohttp>=3.12.14 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow-providers-http->apache-airflow) (3.13.3)\n",
      "Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from aiohttp>=3.12.14->apache-airflow-providers-http->apache-airflow) (2.6.1)\n",
      "Requirement already satisfied: aiosignal>=1.4.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from aiohttp>=3.12.14->apache-airflow-providers-http->apache-airflow) (1.4.0)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from aiohttp>=3.12.14->apache-airflow-providers-http->apache-airflow) (1.4.0)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from aiohttp>=3.12.14->apache-airflow-providers-http->apache-airflow) (6.0.4)\n",
      "Requirement already satisfied: propcache>=0.2.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from aiohttp>=3.12.14->apache-airflow-providers-http->apache-airflow) (0.4.1)\n",
      "Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from aiohttp>=3.12.14->apache-airflow-providers-http->apache-airflow) (1.22.0)\n",
      "Requirement already satisfied: aiosmtplib>=0.1.6 in c:\\users\\shiim\\anaconda3\\lib\\site-packages (from apache-airflow-providers-smtp->apache-airflow) (5.0.0)\n"
     ]
    }
   ],
   "source": [
    "!pip install requests\n",
    "!pip install apache-airflow"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "13fb890f-3970-4af3-838c-db7c542c82a9",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "import logging\n",
    "from urllib3.util.retry  import Retry\n",
    "import requests\n",
    "from airflow.sdk.bases.hook import BaseHook\n",
    "from requests.adapters import HTTPAdapter\n",
    "from airflow.exceptions import AirflowException\n",
    "from typing import List,Dict,Any\n",
    "import time\n",
    "\n",
    "\n",
    "\n",
    "logger =logging.getLogger(__name__)\n",
    "\n",
    "\n",
    "\n",
    "class FinnhubAPI(BaseHook):\n",
    "    conn_name_attr = \"api_conn_id\"\n",
    "    default_conn_name = \"finnhub_default\"\n",
    "    conn_type = \"http\"\n",
    "    hook_name = \"Finnhub\"\n",
    "    base_url = \"https://api.finnhub.io/api/v1\"\n",
    "    default_timeout = 10\n",
    "    \n",
    "\n",
    "\n",
    "    def __init__(\n",
    "        self,\n",
    "        api_conn_id:str = default_conn_name,\n",
    "        base_url:str = base_url,\n",
    "        max_retries:int = 3,\n",
    "        timeout:int = default_timeout,\n",
    "        rate_limit_per_min:int = 60,\n",
    "        ):\n",
    "        super().__init__()\n",
    "        self.api_conn_id = api_conn_id\n",
    "        self.base_url = base_url\n",
    "        self.max_retries = max_retries\n",
    "        self.timeout = timeout\n",
    "        self.rate_limit_per_min = rate_limit_per_min\n",
    "        self._session = None\n",
    "        \n",
    "\n",
    "    def get_api_key(self)->str:\n",
    "\n",
    "        \"\"\"The Api_key is provided directly in the Finnhub Documentation.\n",
    "        But i have chosen the get_connection() functionality to add a security layer.\n",
    "        Though,the Api key will be displayed on the Apache Airflow UI Dashboard\"\"\"\n",
    "\n",
    "        conn = self.get_connection(self.api_conn_id)\n",
    "        if not conn.password:\n",
    "            raise AirflowException(\n",
    "                f\"No API key found for the connection. Set the correct API Key\")\n",
    "        return conn.password         \n",
    "        \n",
    "        \n",
    "    def _conn_session(self)-> requests.Session:\n",
    "        if self._session is None:\n",
    "            self._session = requests.Session()\n",
    "            self._session.headers.update({\"Accept\": \"application/json\",\n",
    "                                \"User-Agent\": \"finnhub/python\"})\n",
    "            self._session.params[\"token\"] = self.get_api_key()\n",
    "\n",
    "            retry_attributes = Retry(\n",
    "                total = self.max_retries,\n",
    "                backoff_factor = 3,\n",
    "                status_forcelist= [429,500,502,503,504],\n",
    "                allowed_methods = [\"GET\"]\n",
    "            )\n",
    "            adapter = HTTPAdapter(max_retries = retry_attributes)\n",
    "            self._session.mount(\"https://\",adapter)\n",
    "            self._session.mount(\"http://\",adapter)\n",
    "        return self._session\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "    def fetch_data(self, name:str)-> Dict[str,Any]:\n",
    "        session = self._conn_session()\n",
    "        parameters = {\n",
    "           \"symbol\": name\n",
    "        }\n",
    "        web_url = f\"{self.base_url}/quote\"\n",
    "\n",
    "        logger.info(\"Fetching Financial Data!\")\n",
    "        response = session.get(web_url , params = parameters, timeout = self.timeout)\n",
    "        if response.status_code == 429:\n",
    "            logger.warning(f\"Rate Limit Hit for {name}! Tenacity will retry...\")\n",
    "            response.raise_for_status() \n",
    "\n",
    "        try:\n",
    "            response.raise_for_status()\n",
    "            logger.info(\"Successfully fetched the data!\")\n",
    "            return response.json()\n",
    "            \n",
    "        except requests.exceptions.HTTPError as ERROR:\n",
    "            if ERROR.response.status_code == 401:\n",
    "                # Fatal error: Don't retry, just fail the Airflow task\n",
    "                raise AirflowException(\"Invalid API Key! Check Your Airflow Connection.\")\n",
    "            elif ERROR.response.status_code == 404:\n",
    "                # Missing data: Don't fail the task, just skip this symbol\n",
    "                logger.warning(f\"Symbol {name} not found.\")\n",
    "                return None\n",
    "            raise\n",
    "                \n",
    "                \n",
    "        \n",
    "\n",
    "    def fetch_data_in_batches(self, names: List[str]) -> Dict[str, Any]:\n",
    "        result = {}\n",
    "        delay = 60.00 / self.rate_limit_per_min\n",
    "\n",
    "        for i, name in enumerate(names):\n",
    "            # 1. Apply delay BEFORE the call (except for the first one)\n",
    "            if i > 0:\n",
    "                time.sleep(delay)\n",
    "            \n",
    "            # 2. Call the API once\n",
    "            data = self.fetch_data(name)\n",
    "            \n",
    "            # 3. Store the result in the dictionary\n",
    "            result[name] = data\n",
    "        \n",
    "    # Filter out the Nones (404s) if you only want successful records\n",
    "        successful_results = {k: v for k, v in result.items() if v is not None}\n",
    "        \n",
    "        logger.info(f\"Fetched {len(successful_results)}/{len(names)} symbols successfully.\")\n",
    "        return successful_results\n",
    "        \n",
    "    def test_connection(self):\n",
    "        try:\n",
    "            aapl_data = self.fetch_data(\"AAPL\")\n",
    "            print(f\"AAPL Data: {aapl_data}\")\n",
    "            return True, \"Connection Successful!\"\n",
    "        except Exception as e:\n",
    "            return False, f\"Connection failed: {str(e)}\"\n",
    "        \n",
    "    \n",
    "        \n",
    "    def close(self):\n",
    "        if self._session:\n",
    "            self._session.close()\n",
    "            self._session = None\n",
    "\n",
    "           \n",
    "        \n",
    "            \n",
    "        \n",
    "        \n",
    "\n",
    "        \n",
    "\n",
    "\n",
    "\n",
    "\n",
    "        \n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "aaea89d3-42ee-4373-8a0e-90e61b1c183e",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
