{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "508d9322-eb10-4af4-a915-f76468dc9dca",
   "metadata": {},
   "outputs": [],
   "source": [
    "from datetime import datetime, timedelta\n",
    "from typing import Dict, Any\n",
    "\n",
    "import pandas as pd\n",
    "import io\n",
    "import json\n",
    "import logging\n",
    "import sys\n",
    "\n",
    "from airflow import DAG\n",
    "from airflow.decorators import task\n",
    "from airflow.providers.google.cloud.hooks.bigquery import BigQueryHook\n",
    "from airflow.providers.slack.notifications.slack import send_slack_notification\n",
    "from airflow.exceptions import AirflowException\n",
    "from google.cloud import storage\n",
    "\n",
    "\n",
    "sys.path.insert(0, \"/opt/airflow\")\n",
    "logger = logging.getLogger(__name__)\n",
    "\n",
    "def _write_parquet_to_gcs(df:pd.DataFrame, bucket_name:str, blob_path:str,project:str)-> str:\n",
    "    client = storage.Client(project = project)\n",
    "    bucket = client.bucket(bucket_name)\n",
    "    blob = bucket.blob(blob_path)\n",
    "    buffer = io.BytesIO()\n",
    "    df.to_parquet(buffer, index = False, engine = \"pyarrow\")\n",
    "    buffer.seek(0)\n",
    "    blob.upload_from_file(buffer,content_type = \"application/octet-stream\")\n",
    "    return f\"gs://{bucket_name}/{blob_path}\"\n",
    "\n",
    "def _read_parquet_from_gcs(project:str,bucket_name:str,blob_path:str)-> pd.DataFrame:\n",
    "    client = storage.Client(project = \"project-ba01e344-5e1a-4b59-8d5\")\n",
    "    bucket = client.bucket(\"blob_finnhub\")\n",
    "    blob = bucket.blob(\"blob_finnhub/finnhub_etl\")\n",
    "    buffer = io.BytesIO()\n",
    "    blob.download_to_file(buffer)\n",
    "    buffer.seek(0)\n",
    "    return pd.read_parquet(buffer, engine = \"pyarrow\")\n",
    "\n",
    "def failure_callback(context:Dict[str, Any]):\n",
    "    task_instance_failed = context[\"task_instance\"]\n",
    "    exception = context.get(\"exception\",\"Unknown error\")\n",
    "    logical_date = context.get(\"logical_date\",\"Unknown date\")\n",
    "\n",
    "    message = (\n",
    "        f\"Pipeline Failure\\n\"\n",
    "        f\"DAG: {task_instance_failed.dag_id}\\n\"\n",
    "        f\"Task: {task_instance_failed.task_id}\\n\"\n",
    "        f\"Date: {logical_date}\\n\"\n",
    "        f\"Error:{str(exception)[:500]}\\n\"\n",
    "        f\"Log: {task_instance_failed.log_url}\"\n",
    "    )\n",
    "    logger.error(message)\n",
    "\n",
    "default_args = {\n",
    "    \"owner\":\"finnhub_etl\",\n",
    "    \"depends_on_past\":False,\n",
    "    \"retries\":2,\n",
    "    \"retry_delay\": timedelta(minutes = 5),\n",
    "    \"retry_exponential_backoff\": True,\n",
    "    \"on_failure_callback\": failure_callback,\n",
    "    \"execution_timeout\": timedelta(minutes = 10),\n",
    "    }\n",
    "with DAG(\n",
    "    dag_id = \"Finnhub_ETL\",\n",
    "    default_args = default_args,\n",
    "    start_date = datetime(2026,1,1),\n",
    "    schedule = \"@daily\",\n",
    "    catchup = False,\n",
    "    max_active_runs = 1,\n",
    "    tags = [\"Finnhub\",\"ETL\"],\n",
    "    doc_md = __doc__,\n",
    ") as dag:\n",
    "    @task(\n",
    "        retries = 3,\n",
    "        retry_delay = timedelta(minutes = 2),\n",
    "    )\n",
    "\n",
    "    def extract(logical_date = None, **kwargs)->str:\n",
    "        hook = FinnhubAPI(\n",
    "            api_conn_id = pipeline_config.api.api_conn_id,\n",
    "            timeout = pipeline_config.api.default_timeout,\n",
    "            max_retries = pipeline_config.api.max_retries,\n",
    "            rate_limit_per_min = pipeline_config.api.rate_limit_per_min\n",
    "        )\n",
    "        hook_results = hook.fetch_data_in_batches(list(pipeline_config.api.default_symbols))\n",
    "        if not hook_results:\n",
    "            raise AirflowException(\"No data returned. Got an Empty Response in the form of an empty List\")\n",
    "\n",
    "        records = []\n",
    "        for result in hook_results:\n",
    "            records.append({\n",
    "                \"symbol\": result[\"symbol\"],\n",
    "                \"c\": result[\"c\"],\n",
    "                \"t\": result[\"t\"],\n",
    "                \"o\": result[\"o\"],\n",
    "                \"h\": result[\"h\"],\n",
    "                \"l\": result[\"l\"],\n",
    "                \"v\": result[\"v\"],\n",
    "                \"d\": logical_date.strftime(\"%Y-%m-%d\"),\n",
    "                \"dp\": result[\"dp\"],\n",
    "                \"pc\": result[\"pc\"]\n",
    "            })\n",
    "        df = pd.DataFrame(records)\n",
    "\n",
    "        date_partition = logical_date.strftime(\"%Y-%m-%d\")\n",
    "        gcs_path = f\"{pipeline_config.gcs.raw_prefix}/date={date_partition}/finnhub_data.parquet\"\n",
    "        _write_parquet_to_gcs(df, pipeline_config.gcs.bucket_name, gcs_path, project)\n",
    "        logger.info(f\"Extracted {len(df)} records → gs://{pipeline_config.gcs.bucket_name}/{gcs_path}\")\n",
    "        return gcs_path\n",
    "    \n",
    "    @task\n",
    "    def validate(raw_gcs_path:str, **kwargs) -> str:\n",
    "        bigquery_hook = BigQueryHook(gcp_conn_id = pipeline_config.gcp_conn_id)\n",
    "        project = bigquery_hook.get_client().project\n",
    "        df = _read_parquet_from_gcs(pipeline_config.gcs.bucket,raw_gcs_path,project)\n",
    "        passed,results = Validator.validate_raw_data(df)\n",
    "\n",
    "        if not passed:\n",
    "            fail = [r for r in results if not r.passed and r.severity == \"critical\"]\n",
    "            fail_info = \",\".join([f\"{r.check_name}:{r.message}\"for r in fail])\n",
    "            raise AirflowException(f\"Data Validation Failed:{fail_info}\")\n",
    "        logger.info(\"All Validation Checks Cleared!\")\n",
    "        return raw_gcs_path\n",
    "\n",
    "    @task\n",
    "    def transform(validated_gcs_path:str, logical_date = None, **kwargs) -> Dict[str,str]:\n",
    "        bigquery_hook = BigQueryHook(gcp_conn_id = pipeline_config.gcp_conn_id)\n",
    "        project = bigquery_hook.get_client().project\n",
    "        df = _read_parquet_from_gcs(pipeline_config.gcs.bucket_name,validated_gcs_path,project)\n",
    "        \n",
    "        date_key = int(logical_date.strftime(\"%Y%m%d\"))\n",
    "\n",
    "        dim_symbol = (\n",
    "        df[[\"symbol\"]]\n",
    "        .drop_duplicates()             \n",
    "        .reset_index(drop=True)\n",
    "        )\n",
    "\n",
    "        dim_date = pd.DataFrame([{\n",
    "            \"date_key\": date_key,\n",
    "            \"full_date\": str(date_key),\n",
    "            \"day_name\": logical_date.strftime(\"%A\"),              \n",
    "            \"day_of_week\": logical_date.weekday(),               \n",
    "            \"day_of_month\": logical_date.day,                     \n",
    "            \"week_of_year\": logical_date.isocalendar()[1],       \n",
    "            \"month_name\": logical_date.strftime(\"%B\"),            \n",
    "            \"month_number\": logical_date.month,                   \n",
    "            \"quarter\": f\"Q{(logical_date.month - 1) // 3 + 1}\", \n",
    "            \"year\": logical_date.year,                            \n",
    "            \"is_weekend\": logical_date.weekday() >= 5,            \n",
    "            \"is_month_start\": logical_date.day == 1,              \n",
    "            \"is_month_end\": (                                     \n",
    "                logical_date.month != (logical_date + pd.Timedelta(days=1)).month\n",
    "            ),\n",
    "        }])\n",
    "\n",
    "        fact_df = df.merge(\n",
    "        dim_symbol[[\"ticker\", \"symbol_key\"]],\n",
    "        left_on=\"symbol\",\n",
    "        right_on=\"ticker\",\n",
    "        )\n",
    "\n",
    "\n",
    "        fact_df[\"date_key\"] = date_key\n",
    "\n",
    "        fact_df = fact_df.rename(columns={\n",
    "            \"c\": \"close_price\",\n",
    "            \"o\": \"open_price\",\n",
    "            \"h\": \"high_price\",\n",
    "            \"l\": \"low_price\",\n",
    "            \"pc\": \"previous_close\",\n",
    "            \"d\": \"price_change\",\n",
    "            \"dp\": \"price_change_percent\",\n",
    "        })\n",
    "        fact_columns = [\n",
    "            \"date_key\",\n",
    "            \"symbol_key\",\n",
    "            \"close_price\",\n",
    "            \"open_price\",\n",
    "            \"high_price\",\n",
    "            \"low_price\",\n",
    "            \"previous_close\",\n",
    "            \"price_change\",\n",
    "            \"price_change_percent\",\n",
    "        ]\n",
    "        available_columns = [col for col in fact_columns if col in fact_df.columns]\n",
    "        fact_df = fact_df[available_columns]\n",
    "        fact_df[\"ingestion_date\"] = str(date_key)\n",
    "        tables = {\n",
    "            \"dim_date\": dim_date,\n",
    "            \"dim_symbol\": dim_symbol,\n",
    "            \"fact_daily_quotes\": fact_df,\n",
    "        }\n",
    "\n",
    "        output_paths = {}\n",
    "        for table_name, table_df in tables.items():\n",
    "            path = f\"{pipeline_config.gcs.transformed_prefix}/date={str(date_key)}/{table_name}.parquet\"\n",
    "            _write_parquet_to_gcs(table_df, pipeline_config.gcs.bucket, path, project)\n",
    "            output_paths[table_name] = path\n",
    "            logger.info(f\"Wrote {table_name} ({len(table_df)} rows) → {path}\")\n",
    "\n",
    "        return output_paths\n",
    "\n",
    "    @task\n",
    "    def load(table_paths: Dict[str, str], **kwargs) -> None:\n",
    "        \n",
    "        from google.cloud.bigquery import LoadJobConfig, WriteDisposition\n",
    "\n",
    "        bq_hook = BigQueryHook(gcp_conn_id=pipeline_config.gcp_conn_id)\n",
    "        client = bq_hook.get_client()\n",
    "        dataset = pipeline_config.bigquery.dataset\n",
    "\n",
    "        write_modes = {\n",
    "            \"dim_date\": WriteDisposition.WRITE_TRUNCATE,\n",
    "            \"dim_symbol\": WriteDisposition.WRITE_TRUNCATE,\n",
    "            \"fact_daily_quotes\": WriteDisposition.WRITE_APPEND,\n",
    "        }\n",
    "\n",
    "        for table_name, gcs_path in table_paths.items():\n",
    "            df = _read_parquet_from_gcs(pipeline_config.gcs.bucket, gcs_path, client.project)\n",
    "\n",
    "            table_id = f\"{pipeline_config.bigquery.project}.{dataset}.{table_name}\"\n",
    "            disposition = write_modes.get(table_name, WriteDisposition.WRITE_APPEND)\n",
    "\n",
    "            job_config = LoadJobConfig(write_disposition=disposition)\n",
    "            job = client.load_table_from_dataframe(df, table_id, job_config=job_config)\n",
    "            job.result()  # Wait for completion\n",
    "\n",
    "            logger.info(\n",
    "                f\"Loaded {table_name} → {table_id} \"\n",
    "                f\"({len(df)} rows, mode={disposition})\"\n",
    "            )\n",
    "    raw_path = extract()\n",
    "    validated_path = validate(raw_path)\n",
    "    transformed_paths = transform(validated_path)\n",
    "    load(transformed_paths)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
